// Generated by scripts/generate-theme-table.mjs — do not edit by hand.
// Source: anomalyco/opencode@v2.0.5, packages/tui/src/theme/assets/*.json (MIT).
// Regenerate: node scripts/generate-theme-table.mjs

export const BUILTIN_THEME_BORDERS: Record<
  string,
  { dark: { inactive: string; active: string }; light: { inactive: string; active: string } }
> = {
  "aura": {"dark":{"inactive":"#2d2d2d","active":"#6d6d6d"},"light":{"inactive":"#2d2d2d","active":"#6d6d6d"}},
  "ayu": {"dark":{"inactive":"#6c7380","active":"#6c7380"},"light":{"inactive":"#6c7380","active":"#6c7380"}},
  "carbonfox": {"dark":{"inactive":"#303030","active":"#33b1ff"},"light":{"inactive":"#dcdcdc","active":"#0043ce"}},
  "catppuccin": {"dark":{"inactive":"#313244","active":"#45475a"},"light":{"inactive":"#ccd0da","active":"#bcc0cc"}},
  "catppuccin-frappe": {"dark":{"inactive":"#414559","active":"#51576d"},"light":{"inactive":"#414559","active":"#51576d"}},
  "catppuccin-macchiato": {"dark":{"inactive":"#363a4f","active":"#494d64"},"light":{"inactive":"#363a4f","active":"#494d64"}},
  "cobalt2": {"dark":{"inactive":"#1f4662","active":"#0088ff"},"light":{"inactive":"#d3dae3","active":"#0066cc"}},
  "cursor": {"dark":{"inactive":"#e4e4e4","active":"#88c0d0"},"light":{"inactive":"#141414","active":"#6f9ba6"}},
  "dracula": {"dark":{"inactive":"#44475a","active":"#bd93f9"},"light":{"inactive":"#c8c8c2","active":"#bd93f9"}},
  "everforest": {"dark":{"inactive":"#859289","active":"#9da9a0"},"light":{"inactive":"#939f91","active":"#829181"}},
  "flexoki": {"dark":{"inactive":"#575653","active":"#6f6e69"},"light":{"inactive":"#b7b5ac","active":"#878580"}},
  "github": {"dark":{"inactive":"#30363d","active":"#58a6ff"},"light":{"inactive":"#d0d7de","active":"#0969da"}},
  "gruvbox": {"dark":{"inactive":"#665c54","active":"#ebdbb2"},"light":{"inactive":"#bdae93","active":"#3c3836"}},
  "kanagawa": {"dark":{"inactive":"#54546d","active":"#c38d9d"},"light":{"inactive":"#d4cbbf","active":"#c38d9d"}},
  "lucent-orng": {"dark":{"inactive":"#ec5b2b","active":"#ee7948"},"light":{"inactive":"#ec5b2b","active":"#c94d24"}},
  "material": {"dark":{"inactive":"#37474f","active":"#82aaff"},"light":{"inactive":"#e0e0e0","active":"#6182b8"}},
  "matrix": {"dark":{"inactive":"#1e2a1b","active":"#2eff6a"},"light":{"inactive":"#748476","active":"#1cc24b"}},
  "mercury": {"dark":{"inactive":"#b4b7c8","active":"#8da4f5"},"light":{"inactive":"#707393","active":"#5266eb"}},
  "monokai": {"dark":{"inactive":"#3e3d32","active":"#66d9ef"},"light":{"inactive":"#d0d0d0","active":"#66d9ef"}},
  "nightowl": {"dark":{"inactive":"#5f7e97","active":"#82aaff"},"light":{"inactive":"#5f7e97","active":"#82aaff"}},
  "nord": {"dark":{"inactive":"#434c5e","active":"#4c566a"},"light":{"inactive":"#4c566a","active":"#434c5e"}},
  "one-dark": {"dark":{"inactive":"#393f4a","active":"#61afef"},"light":{"inactive":"#d1d1d2","active":"#4078f2"}},
  "opencode": {"dark":{"inactive":"#484848","active":"#606060"},"light":{"inactive":"#b8b8b8","active":"#a0a0a0"}},
  "orng": {"dark":{"inactive":"#ec5b2b","active":"#ee7948"},"light":{"inactive":"#ec5b2b","active":"#c94d24"}},
  "osaka-jade": {"dark":{"inactive":"#3d4a44","active":"#2dd5b7"},"light":{"inactive":"#a8a78c","active":"#1faa90"}},
  "palenight": {"dark":{"inactive":"#32364a","active":"#82aaff"},"light":{"inactive":"#e0e0e0","active":"#4976eb"}},
  "rosepine": {"dark":{"inactive":"#403d52","active":"#9ccfd8"},"light":{"inactive":"#dfdad9","active":"#31748f"}},
  "solarized": {"dark":{"inactive":"#073642","active":"#586e75"},"light":{"inactive":"#eee8d5","active":"#93a1a1"}},
  "synthwave84": {"dark":{"inactive":"#495495","active":"#36f9f6"},"light":{"inactive":"#e0e0e0","active":"#00bcd4"}},
  "tokyonight": {"dark":{"inactive":"#737aa2","active":"#9099b2"},"light":{"inactive":"#737a8c","active":"#5a607d"}},
  "vercel": {"dark":{"inactive":"#1f1f1f","active":"#454545"},"light":{"inactive":"#eaeaea","active":"#999999"}},
  "vesper": {"dark":{"inactive":"#282828","active":"#ffc799"},"light":{"inactive":"#d0d0d0","active":"#ffc799"}},
  "zenburn": {"dark":{"inactive":"#5f5f5f","active":"#8cd0d3"},"light":{"inactive":"#d0d0c0","active":"#5f7f8f"}},
};
